[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && npm start"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[build.nixpacksPlan]
providers = ["nodejs"]

[build.nixpacksPlan.phases.setup]
nixPkgs = ["nodejs", "npm"]

[build.nixpacksPlan.phases.install]
cmds = ["cd backend && npm install"]

[build.nixpacksPlan.phases.build]
cmds = ["echo 'No build step required'"]
