// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmwgp87vNNyBR7pRO2mmVLeNj7VApndvs',
    appId: '1:278357859589:web:1dc5be63d203953ffdeb6c',
    messagingSenderId: '278357859589',
    projectId: 'prohobby-checklist',
    authDomain: 'prohobby-checklist.firebaseapp.com',
    storageBucket: 'prohobby-checklist.firebasestorage.app',
    measurementId: 'G-2JNG9ME3QE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBYxSNkvbOloCIB9z7xVg_QwPMkCj08kAs',
    appId: '1:278357859589:android:dcc7dcea733462e6fdeb6c',
    messagingSenderId: '278357859589',
    projectId: 'prohobby-checklist',
    storageBucket: 'prohobby-checklist.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_l3Lbf49VGocr6bvq34LaCcm1ggMwH54',
    appId: '1:278357859589:ios:79370374a1123b5ffdeb6c',
    messagingSenderId: '278357859589',
    projectId: 'prohobby-checklist',
    storageBucket: 'prohobby-checklist.firebasestorage.app',
    iosBundleId: 'com.prohobby.checklistApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_l3Lbf49VGocr6bvq34LaCcm1ggMwH54',
    appId: '1:278357859589:ios:79370374a1123b5ffdeb6c',
    messagingSenderId: '278357859589',
    projectId: 'prohobby-checklist',
    storageBucket: 'prohobby-checklist.firebasestorage.app',
    iosBundleId: 'com.prohobby.checklistApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBmwgp87vNNyBR7pRO2mmVLeNj7VApndvs',
    appId: '1:278357859589:web:76ccfb285efcbe78fdeb6c',
    messagingSenderId: '278357859589',
    projectId: 'prohobby-checklist',
    authDomain: 'prohobby-checklist.firebaseapp.com',
    storageBucket: 'prohobby-checklist.firebasestorage.app',
    measurementId: 'G-0ZMW1T3PXC',
  );
}
